apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: team-green
  name: team-green
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: team-green
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
