apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: team-blue
  name: team-blue
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: team-blue
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
