apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: team-green
  name: team-green
spec:
  replicas: 1
  selector:
    io.kompose.service: team-green
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: team-green
    spec:
      containers:
      - image: ' '
        name: team-green
        ports:
        - containerPort: 3002
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - team-green
      from:
        kind: ImageStreamTag
        name: team-green:latest
    type: ImageChange
status: {}
