apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: team-red
  name: team-red
spec:
  ports:
  - name: "3003"
    port: 3003
    targetPort: 3003
  selector:
    io.kompose.service: team-red
status:
  loadBalancer: {}
