apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: team-red
  name: team-red
spec:
  replicas: 1
  selector:
    io.kompose.service: team-red
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: team-red
    spec:
      containers:
      - image: ' '
        name: team-red
        ports:
        - containerPort: 3003
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - team-red
      from:
        kind: ImageStreamTag
        name: team-red:latest
    type: ImageChange
status: {}
